### ISSUE TITLE
Enhance Documentation

### ISSUE THREAD

**Issue by jwaspin** [jwaspin/luca-ledger#76]
Like really enhance the documentation. Done right.

This should also include a home page that explains Luca Ledger to the users, not just enhancing the README documentation in this repository.

**Comment by kendrajohng** [comment]
@jwaspin I started a user guide for Luca Ledger! This is my first time contributing to an open-source project, but I'm excited to work on this. If you have some time, could you please review and provide feedback on the PDF I'm attaching? I appreciate it, and I hope we can continue to work on your project's documentation. I'm assuming you're looking for instructions to be in-app, but I would need a little guidance on adding a help page to your application. I currently have limited working knowledge of HTML, CSS, and JS, but I'm willing to learn!

[Luca-Ledger Documentation_jwaspin_112723.pdf](https://github.com/jwaspin/luca-ledger/files/13483146/Luca-Ledger.Documentation_jwaspin_112723.pdf)

**Comment by jwaspin** [comment]
@kendrajohng Thank you!!! That looks amazing! Sorry for the delayed response, I missed this due to the holidays and am just now getting back in here. I'm working on this in my spare time but I plan to keep updating things throughout the year so if you make updates to the user guide I will happily incorporate them into the repo!
